server:
  port: 8080

spring:
  application:
    name: message-service

    # rocketMQ 配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: GROUP_MESSAGE_PRODUCER
    send message timeout: 3000
  client:
    logPath: D:\Arjmast

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    com.jobconnect: DEBUG