server:
  port: 8080

spring:
  application:
    name: message-service

 # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0

    # rocketMQ 配置
rocketmq:
  name-server: 1kt0362to8824.vicp.fun:58004
  producer:
    group: GROUP_MESSAGE_PRODUCER
    send message timeout: 3000
  client:
    logPath: D:\Arjmast

logging:
  file:
    name: logs/application.log
    encoding: UTF-8
  level:
    root: INFO
    com.jobconnect: DEBUG